#!/bin/bash

if [ ! -f /home/victor/crontab_backup ]; then
 cat /etc/crontab > /home/victor/crontab_backup
fi

backup_md5=$( md5sum /home/victor/crontab_backup | awk '{print $1}' )
cron_md5=$( md5sum /etc/crontab | awk '{print $1}' )

if [ "$backup_md5" != "$cron_md5" ]; then
	echo "crontab changed"
	echo "crontab changed" | mail -s "your crontab has changed" root
	cat /etc/crontab > /home/victor/crontab_backup
	exit 1
else
	echo "nothing changed"
	 exit 2
 fi
# pour executer le cron tous les jours a minuit
# commande shell sudo crontab -u root -e
# editer le fichier crontab en rajoutant "0 0 * * /absolute/path/to/the/file"
